apiVersion: apps/v1
kind: Deployment
metadata:
  name: success-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: success-app
  template:
    metadata:
      labels:
        app: success-app
    spec:
      containers:
      - name: success-app
        image: tranxi/success-app:v2
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /live
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---

apiVersion: v1
kind: Service
metadata:
  name: success-service
spec:
  type: LoadBalancer
  selector:
    app: success-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
